language: node_js

notifications:
  email: false

node_js:
  - stable

cache:
  directories:
    - "node_modules"
    - "public"
    - ~/.npm
git:
  depth: 3

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

before_install:
  - npm i -g npm@5.5.1

install: npm install

script:
  - npm test
